# Generated by Django 6.0.6 on 2026-06-25 14:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('geom_type', models.CharField(choices=[('poing', 'Point (ตำแหน่งการถ่ายภาพ)'), ('line', 'Line (ถ่ายวิดีโอเส้นทาง)'), ('polygon', 'Polygon (ทำแผนที่ / โดรนเกษตร)')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('address_text', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'เปิดรับสมัคร'), ('MATCHED', 'จับคู่สำเร็จ'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('COMPLETED', 'เสร็จสิ้น'), ('CANCELED', 'ยกเลิก')], default='PENDING', max_length=50)),
                ('deadline', models.DateField(help_text='เดดไลน์การเปิดรับสมัคร')),
                ('start_date', models.DateTimeField(help_text='วันเวลานัดหมายเริ่มบิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='app_boarding.jobcategory')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
