# Generated by Django 6.0.6 on 2026-06-26 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boarding', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคาที่เสนอ')),
                ('available_dates', models.DateField(help_text='วันที่ที่สามารถทำงานได้')),
                ('status', models.CharField(choices=[('PENDING', 'รอการตอบรับ'), ('ACCEPTED', 'ผ่านการคัดเลือก'), ('REJECTED', 'ปฏิเสธการคัดเลือก')], default='PENDING', max_length=50)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app_boarding.jobposting')),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('job', 'pilot')},
            },
        ),
    ]
