# Generated by Django 6.0.6 on 2026-06-26 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_boarding', '0002_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(verbose_name='URL ของไฟล์')),
                ('note', models.TextField(blank=True, null=True, verbose_name='บันทึกข้อมูลเพิ่มเติม')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='app_boarding.jobapplication')),
            ],
        ),
    ]
