# Generated by Django 6.0.6 on 2026-06-26 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_num', models.CharField(max_length=20, unique=True, verbose_name='เลขที่ใบอนุญาต')),
                ('phone', models.CharField(max_length=10, verbose_name='หมายเลขโทรศัพท์')),
                ('drone_model', models.CharField(max_length=255, verbose_name='รุ่นโดรน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
